name: CI-CD TaskFlow

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  test-selenium:
    runs-on: ubuntu-latest
    needs: test-unit
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: sudo apt-get install -y chromium-browser
      - run: npm run test:selenium

  build:
    runs-on: ubuntu-latest
    needs: test-selenium
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t taskflow .

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build & Push
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/taskflow:${{ github.run_number }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/taskflow:${{ github.run_number }}
